spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://54.180.155.179/aws?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update # ?????? ?? ? ???? ???? ??? ?? ????

  # CORS ??
  web:
    cors:
      allowed-origins: http://localhost:3000
